---
- name: Install Apache and Upload my Web Page to Nginx
  hosts: all
  become: true

  tasks:
    - name: Install, configure, and start Apache
      block:
       - name: Install httpd and memcached
         apt:
           name:
           - memcached
           state: present
      when: ansible_os_family == "Debian"

      #- block:
      #- apt:
      #  name:
      #    - apache2
      #    - memcached
      # state: latest
      # become: true
      # when: ansible_os_family == "Debian"
